import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/badge.tsx',
    'src/button.tsx',
    'src/calendar.tsx',
    'src/checkbox.tsx',
    'src/combobox.tsx',
    'src/command.tsx',
    'src/data-list.tsx',
    'src/data-table.tsx',
    'src/date-picker.tsx',
    'src/datetime-input.tsx',
    'src/dialog.tsx',
    'src/dropdown-menu.tsx',
    'src/form.tsx',
    'src/input.tsx',
    'src/label.tsx',
    'src/otp-input.tsx',
    'src/phone-input.tsx',
    'src/popover.tsx',
    'src/qr-code.tsx',
    'src/radio.tsx',
    'src/select.tsx',
    'src/sortable.tsx',
    'src/switch.tsx',
    'src/textarea.tsx',
    'src/time-picker.tsx',
    'src/tooltip.tsx',
    'src/virtual-list.tsx',
  ],
  format: ['esm'],
  dts: false,
  clean: true,
  sourcemap: true,
  treeshake: true,
  splitting: false,
  minify: false,
  target: 'es2022',
  external: [
    '@stalk-ui/i18n',
    '@stalk-ui/preset',
    'react',
    'react-dom',
    /^@radix-ui\//,
    /^styled-system\//,
    // Third-party runtime deps the consumer installs; keep them out of the
    // measured bundle (their footprint is governed by check-third-party-size).
    'cmdk',
    'input-otp',
    'react-day-picker',
    'react-hook-form',
    'react-international-phone',
    'react-qrcode-logo',
    /^@tanstack\//,
    /^@dnd-kit\//,
  ],
})
