import type { RecipeConfig } from '../types'

export const chart = {
  className: 'stalk-chart',
  description: 'Slot recipe for the Chart theming contract (consumers bring their own recharts).',
  slots: ['container', 'tooltip', 'tooltipLabel', 'tooltipRow', 'tooltipIndicator', 'legend'],
  base: {
    // Themes the recharts DOM via semantic tokens without importing recharts.
    container: {
      display: 'flex',
      justifyContent: 'center',
      aspectRatio: 'video',
      inlineSize: 'full',
      fontSize: 'xs',
      color: 'fg.muted',
      '& .recharts-cartesian-axis-tick text': { fill: 'fg.muted' },
      '& .recharts-cartesian-grid line[stroke="#ccc"]': { stroke: 'border.muted' },
      '& .recharts-curve.recharts-tooltip-cursor': { stroke: 'border.default' },
      '& .recharts-polar-grid [stroke="#ccc"]': { stroke: 'border.muted' },
      '& .recharts-radial-bar-background-sector': { fill: 'bg.subtle' },
      '& .recharts-rectangle.recharts-tooltip-cursor': { fill: 'bg.subtle' },
      '& .recharts-reference-line [stroke="#ccc"]': { stroke: 'border.default' },
      '& .recharts-sector[stroke="#fff"]': { stroke: 'transparent' },
      '& .recharts-dot[stroke="#fff"]': { stroke: 'transparent' },
      '& .recharts-layer': { outline: 'none' },
      '& .recharts-surface': { outline: 'none' },
    },
    tooltip: {
      display: 'grid',
      minInlineSize: '128',
      alignItems: 'start',
      gap: '6',
      rounded: 'md',
      border: 'default',
      bgColor: 'bg.default',
      px: '10',
      py: '6',
      fontSize: 'xs',
      color: 'fg.default',
      shadow: 'md',
    },
    tooltipLabel: {
      fontWeight: 'medium',
      color: 'fg.default',
    },
    tooltipRow: {
      display: 'flex',
      alignItems: 'center',
      gap: '6',
      inlineSize: 'full',
      color: 'fg.muted',
      '& > span:last-child': {
        marginInlineStart: 'auto',
        color: 'fg.default',
        fontWeight: 'medium',
      },
    },
    tooltipIndicator: {
      blockSize: '10',
      inlineSize: '10',
      flexShrink: 0,
      rounded: 'xs',
      bgColor: 'var(--color-indicator, currentColor)',
    },
    legend: {
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '12',
      pt: '12',
      fontSize: 'xs',
      color: 'fg.muted',
      '& > div': { display: 'inline-flex', alignItems: 'center', gap: '6' },
    },
  },
} satisfies RecipeConfig
