import type { RecipeConfig } from '../types'

export const dialog = {
  className: 'stalk-dialog',
  description: 'Slot recipe for Radix-backed dialog layouts.',
  slots: ['overlay', 'content', 'header', 'title', 'description', 'footer', 'close'],
  base: {
    overlay: {
      pos: 'fixed',
      inset: '0',
      bgColor: 'black.a8',
      zIndex: 'modal',
    },
    content: {
      pos: 'fixed',
      insetInlineStart: '50%',
      insetBlockStart: '50%',
      w: 'min(calc(100vw - 2rem), 32rem)',
      maxH: 'calc(100vh - 2rem)',
      overflow: 'auto',
      transform: 'translate(-50%, -50%)',
      bgColor: 'bg.default',
      border: 'default',
      rounded: 'lg',
      shadow: 'lg',
      color: 'fg.default',
      p: '24',
      zIndex: 'modal',
    },
    header: {
      display: 'grid',
      gap: '6',
      pb: 'base',
      pe: '32',
    },
    title: {
      textStyle: 'h5',
    },
    description: {
      color: 'fg.muted',
      textStyle: 'bodySm',
    },
    footer: {
      alignItems: 'center',
      display: 'flex',
      gap: '12',
      justifyContent: 'flex-end',
      pt: 'base',
    },
    close: {
      pos: 'absolute',
      insetBlockStart: '12',
      insetInlineEnd: '12',
      alignItems: 'center',
      appearance: 'none',
      bgColor: 'transparent',
      border: 'none',
      rounded: 'sm',
      color: 'fg.muted',
      cursor: 'pointer',
      display: 'inline-flex',
      flexShrink: 0,
      font: 'inherit',
      h: '28',
      justifyContent: 'center',
      lineHeight: 1,
      m: '0',
      p: '0',
      w: '28',
      _hover: {
        bgColor: 'bg.subtle',
        color: 'fg.default',
      },
      _focusVisible: {
        focusRingWidth: 'base',
        focusRingColor: 'accent.subtle',
        focusRingOffsetWidth: '1',
        focusRingOffsetColor: 'bg.default',
      },
      '& > svg': {
        flexShrink: 0,
        h: '16',
        w: '16',
      },
    },
  },
} satisfies RecipeConfig
