import type { RecipeConfig } from '../types'

export const fileUpload = {
  className: 'stalk-file-upload',
  jsx: ['FileUpload', /^FileUpload\./],
  description:
    'Slot recipe for FileUpload / Dropzone (drop target with drag state, hint, and selected-file list).',
  slots: [
    'root',
    'dropzone',
    'icon',
    'label',
    'hint',
    'list',
    'item',
    'itemName',
    'itemSize',
    'remove',
  ],
  base: {
    root: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8',
      w: 'full',
    },
    dropzone: {
      alignItems: 'center',
      appearance: 'none',
      bgColor: 'bg.canvas',
      borderColor: 'border.default',
      borderRadius: 'md',
      borderStyle: 'dashed',
      borderWidth: '1px',
      color: 'fg.muted',
      cursor: 'pointer',
      display: 'flex',
      flexDirection: 'column',
      font: 'inherit',
      gap: '6',
      justifyContent: 'center',
      px: '24',
      py: '32',
      textAlign: 'center',
      transitionDuration: 'fast',
      transitionProperty: 'background-color, border-color',
      w: 'full',
      _hover: { bgColor: 'bg.subtle', borderColor: 'border.hover' },
      '&[data-dragging]': { bgColor: 'accent.surface', borderColor: 'accent.solid' },
      _disabled: { cursor: 'not-allowed', opacity: 0.5 },
      _focusVisible: {
        focusRingWidth: 'base',
        focusRingColor: 'accent.muted',
        focusRingOffsetWidth: '2',
        focusRingOffsetColor: 'bg.default',
      },
    },
    icon: {
      color: 'fg.subtle',
      display: 'inline-flex',
    },
    label: {
      color: 'fg.default',
      fontWeight: 'medium',
      m: '0',
      textStyle: 'bodySm',
    },
    hint: {
      color: 'fg.muted',
      fontSize: 'xs',
      m: '0',
    },
    list: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4',
      listStyle: 'none',
      m: '0',
      p: '0',
    },
    item: {
      alignItems: 'center',
      bgColor: 'bg.subtle',
      borderRadius: 'sm',
      display: 'flex',
      gap: '8',
      px: '10',
      py: '6',
      textStyle: 'bodySm',
    },
    itemName: {
      color: 'fg.default',
      flex: '1',
      minW: '0',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    itemSize: {
      color: 'fg.subtle',
      flexShrink: 0,
      fontSize: 'xs',
    },
    remove: {
      alignItems: 'center',
      appearance: 'none',
      bgColor: 'transparent',
      border: 'none',
      borderRadius: 'sm',
      color: 'fg.muted',
      cursor: 'pointer',
      display: 'inline-flex',
      flexShrink: 0,
      justifyContent: 'center',
      p: '2',
      _hover: { bgColor: 'bg.muted', color: 'fg.default' },
    },
  },
} satisfies RecipeConfig
