import type { RecipeConfig } from '../types'

export const navigationMenu = {
  className: 'stalk-navigation-menu',
  description: 'Slot recipe for Radix-backed navigation menus with per-item dropdown panels.',
  jsx: [
    'NavigationMenu',
    'NavigationMenuSub',
    'NavigationMenuRoot',
    'NavigationMenuList',
    'NavigationMenuItem',
    'NavigationMenuTrigger',
    'NavigationMenuContent',
    'NavigationMenuLink',
    /^NavigationMenu\./,
  ],
  slots: ['root', 'list', 'item', 'trigger', 'triggerIcon', 'content', 'link'],
  base: {
    root: {
      pos: 'relative',
      display: 'inline-flex',
      maxW: 'max-content',
      alignItems: 'center',
    },
    list: {
      display: 'flex',
      listStyle: 'none',
      alignItems: 'center',
      gap: '4',
      m: '0',
      p: '0',
    },
    // Positioning context for the dropdown so each panel anchors under its own trigger.
    item: {
      pos: 'relative',
    },
    trigger: {
      alignItems: 'center',
      appearance: 'none',
      bgColor: 'transparent',
      border: 'none',
      color: 'fg.default',
      cursor: 'pointer',
      display: 'inline-flex',
      fontSize: 'sm',
      fontWeight: 'medium',
      gap: '4',
      h: '36',
      m: '0',
      px: '12',
      rounded: 'sm',
      userSelect: 'none',
      _hover: { bgColor: 'bg.subtle' },
      '&[data-state="open"]': { bgColor: 'accent.subtle', color: 'accent.fg' },
      '&[data-state="open"] svg': { transform: 'rotate(180deg)' },
      _focusVisible: {
        focusRingWidth: 'base',
        focusRingColor: 'accent.subtle',
        focusRingOffsetWidth: '1',
        focusRingOffsetColor: 'bg.default',
      },
    },
    triggerIcon: {
      h: '14',
      w: '14',
      flexShrink: 0,
      color: 'fg.muted',
      transitionProperty: 'transform',
      transitionDuration: 'fast',
      '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0s' },
    },
    // Anchored directly under its trigger (no shared viewport), so the panel
    // always lines up with the item that opened it. Sits flush against the
    // trigger row to avoid a hover dead-zone between trigger and panel.
    content: {
      pos: 'absolute',
      top: '100%',
      insetInlineStart: '0',
      zIndex: 'popover',
      minW: '12rem',
      mt: '4',
      bgColor: 'bg.default',
      border: 'default',
      rounded: 'md',
      shadow: 'lg',
      color: 'fg.default',
      p: '8',
      transformOrigin: 'top',
      animationDuration: 'fast',
      animationTimingFunction: 'ease-out',
      '&[data-state="open"]': { animationName: 'scale-in' },
      '&[data-state="closed"]': { animationName: 'scale-out' },
      '@media (prefers-reduced-motion: reduce)': { animationDuration: '0s' },
      '& ul': { listStyle: 'none', display: 'grid', gap: '2', m: '0', p: '0' },
    },
    link: {
      display: 'block',
      rounded: 'sm',
      color: 'fg.default',
      fontSize: 'sm',
      px: '12',
      py: '8',
      textDecoration: 'none',
      _hover: { bgColor: 'bg.subtle' },
      '&[data-active]': { bgColor: 'accent.subtle', color: 'accent.fg' },
      _focusVisible: {
        focusRingWidth: 'base',
        focusRingColor: 'accent.subtle',
        focusRingOffsetWidth: '1',
        focusRingOffsetColor: 'bg.default',
      },
    },
  },
} satisfies RecipeConfig
