import type { RecipeConfig } from '../types'

export const sidebar = {
  className: 'stalk-sidebar',
  description: 'Slot recipe for the collapsible application sidebar composite.',
  jsx: [
    'Sidebar',
    'SidebarProvider',
    'SidebarRoot',
    'SidebarTrigger',
    'SidebarRail',
    'SidebarInset',
    'SidebarHeader',
    'SidebarFooter',
    'SidebarContent',
    'SidebarGroup',
    'SidebarGroupLabel',
    'SidebarMenu',
    'SidebarMenuItem',
    'SidebarMenuButton',
    /^Sidebar\./,
  ],
  slots: [
    'provider',
    'root',
    'backdrop',
    'inset',
    'trigger',
    'rail',
    'header',
    'footer',
    'content',
    'group',
    'groupLabel',
    'menu',
    'menuItem',
    'menuButton',
  ],
  base: {
    provider: {
      display: 'flex',
      minBlockSize: '100vh',
      inlineSize: 'full',
      '--sidebar-width': '16rem',
      '--sidebar-width-collapsed': '3.5rem',
    },
    root: {
      display: 'flex',
      flexDirection: 'column',
      flexShrink: 0,
      blockSize: '100dvh',
      inlineSize: 'var(--sidebar-width)',
      bgColor: 'bg.canvas',
      borderInlineEndWidth: '1px',
      borderColor: 'border.default',
      color: 'fg.default',
      overflow: 'hidden',
      transitionProperty: 'inline-size, transform',
      transitionDuration: 'normal',
      transitionTimingFunction: 'ease',
      '@media (prefers-reduced-motion: reduce)': { transitionDuration: '0ms' },
      '&[data-state="collapsed"]': { inlineSize: 'var(--sidebar-width-collapsed)' },
      // Mobile: off-canvas overlay anchored to the inline-start edge.
      '&[data-mobile="true"]': {
        position: 'fixed',
        insetBlock: '0',
        insetInlineStart: '0',
        zIndex: 'modal',
        inlineSize: 'var(--sidebar-width)',
        boxShadow: 'lg',
        transform: 'translateX(-100%)',
      },
      '&[data-mobile="true"][data-state="expanded"]': { transform: 'translateX(0)' },
    },
    backdrop: {
      position: 'fixed',
      inset: '0',
      zIndex: 'overlay',
      bgColor: 'black/40',
      border: 'none',
      cursor: 'pointer',
    },
    inset: {
      position: 'relative',
      display: 'flex',
      flexDirection: 'column',
      flex: '1',
      minInlineSize: '0',
    },
    trigger: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      blockSize: '32',
      inlineSize: '32',
      rounded: 'sm',
      color: 'fg.default',
      cursor: 'pointer',
      outline: 'none',
      bgColor: 'transparent',
      border: 'none',
      '& > svg': { h: '18', w: '18' },
      _hover: { bgColor: 'bg.subtle' },
      _focusVisible: {
        focusRingWidth: 'base',
        focusRingColor: 'accent.subtle',
        focusRingOffsetWidth: '1',
        focusRingOffsetColor: 'bg.default',
      },
    },
    rail: {
      position: 'absolute',
      insetBlock: '0',
      insetInlineEnd: '-2',
      inlineSize: '4',
      cursor: 'ew-resize',
      bgColor: 'transparent',
      border: 'none',
      outline: 'none',
      transitionProperty: 'background-color',
      transitionDuration: 'fast',
      _hover: { bgColor: 'border.default' },
      _focusVisible: { bgColor: 'accent.muted' },
    },
    header: {
      display: 'flex',
      alignItems: 'center',
      gap: '8',
      p: '8',
      minBlockSize: '48',
      overflow: 'hidden',
      // Collapsed: hide text labels (same convention as menu items) so the title
      // doesn't peek past the icon rail.
      '[data-state="collapsed"] & span': { display: 'none' },
    },
    footer: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4',
      marginBlockStart: 'auto',
      p: '8',
      overflow: 'hidden',
      '[data-state="collapsed"] & span': { display: 'none' },
    },
    content: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8',
      flex: '1',
      overflowX: 'hidden',
      overflowY: 'auto',
      p: '8',
    },
    group: {
      display: 'flex',
      flexDirection: 'column',
      gap: '2',
    },
    groupLabel: {
      px: '8',
      py: '4',
      color: 'fg.muted',
      fontSize: 'xs',
      fontWeight: 'semibold',
      textTransform: 'uppercase',
      letterSpacing: 'wide',
      whiteSpace: 'nowrap',
      '[data-state="collapsed"] &': { display: 'none' },
    },
    menu: {
      display: 'flex',
      flexDirection: 'column',
      gap: '2',
      listStyle: 'none',
      m: '0',
      p: '0',
    },
    menuItem: {
      position: 'relative',
    },
    menuButton: {
      display: 'flex',
      alignItems: 'center',
      gap: '8',
      inlineSize: 'full',
      minBlockSize: '32',
      px: '8',
      rounded: 'sm',
      color: 'fg.default',
      textAlign: 'start',
      textDecoration: 'none',
      cursor: 'pointer',
      bgColor: 'transparent',
      border: 'none',
      outline: 'none',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      '& > svg': { h: '16', w: '16', flexShrink: 0 },
      _hover: { bgColor: 'bg.subtle' },
      _focusVisible: {
        focusRingWidth: 'base',
        focusRingColor: 'accent.subtle',
        focusRingOffsetWidth: '1',
        focusRingOffsetColor: 'bg.default',
      },
      '&[data-active="true"]': {
        bgColor: 'accent.subtle',
        color: 'accent.fg',
        fontWeight: 'medium',
      },
      '[data-state="collapsed"] & > span': { display: 'none' },
    },
  },
} satisfies RecipeConfig
