import type { RecipeConfig } from '../types'

export const textEditor = {
  className: 'stalk-text-editor',
  description: 'Slot recipe for the Tiptap-backed rich text editor.',
  jsx: [
    'TextEditor',
    'TextEditorRoot',
    'TextEditorToolbar',
    'TextEditorContent',
    'TextEditorBubbleMenu',
    'TextEditorMarkButton',
    'TextEditorBlockSelect',
    'TextEditorAlignSelect',
    'TextEditorColorButton',
    'TextEditorLinkButton',
    'TextEditorEmojiButton',
    'TextEditorHistoryButtons',
    'TextEditorCounter',
    /^TextEditor\./,
  ],
  slots: ['root', 'toolbar', 'content', 'bubble', 'counter', 'swatch'],
  base: {
    root: {
      display: 'flex',
      flexDirection: 'column',
      bgColor: 'bg.default',
      border: 'default',
      rounded: 'md',
      overflow: 'hidden',
      transitionDuration: 'fast',
      transitionProperty: 'border-color, box-shadow',
      _focusWithin: {
        border: 'focus',
        focusRingWidth: 'base',
        focusRingColor: 'accent.subtle',
        focusRingOffsetWidth: '1',
        focusRingOffsetColor: 'bg.default',
      },
      '&[data-invalid]': { border: 'invalid' },
      '&[data-disabled]': { opacity: 0.5, pointerEvents: 'none' },
    },
    toolbar: {
      display: 'flex',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: '2',
      px: '8',
      py: '6',
      borderBottomWidth: '1px',
      borderBottomStyle: 'solid',
      borderBottomColor: 'border.muted',
    },
    // The editable surface, including the rendered rich-content typography.
    content: {
      px: '12',
      py: '10',
      minH: '112',
      overflowY: 'auto',
      cursor: 'text',
      '& .tiptap': { outline: 'none', minH: 'inherit' },
      '& p': { marginBlock: '4' },
      '& h1': { fontSize: 'xl', fontWeight: 'semibold', marginBlock: '10' },
      '& h2': { fontSize: 'lg', fontWeight: 'semibold', marginBlock: '8' },
      '& h3': { fontSize: 'base', fontWeight: 'semibold', marginBlock: '6' },
      '& ul:not([data-type="taskList"])': { listStyle: 'disc', ps: '20', marginBlock: '4' },
      '& ol': { listStyle: 'decimal', ps: '20', marginBlock: '4' },
      '& ul[data-type="taskList"]': {
        listStyle: 'none',
        ps: '2',
        marginBlock: '4',
        '& li': { display: 'flex', alignItems: 'flex-start', gap: '8' },
        '& input[type="checkbox"]': { mt: '4' },
      },
      '& blockquote': {
        borderInlineStartWidth: '2px',
        borderInlineStartStyle: 'solid',
        borderInlineStartColor: 'border.default',
        ps: '12',
        color: 'fg.muted',
        marginBlock: '8',
      },
      '& code': {
        bgColor: 'bg.subtle',
        rounded: 'sm',
        px: '4',
        fontFamily: 'mono',
        fontSize: 'sm',
      },
      '& pre': {
        bgColor: 'bg.subtle',
        rounded: 'md',
        p: '12',
        overflowX: 'auto',
        marginBlock: '8',
        '& code': { bgColor: 'transparent', p: '0' },
      },
      '& hr': {
        borderColor: 'border.muted',
        marginBlock: '12',
      },
      '& a': { color: 'accent.text', textDecoration: 'underline' },
      // Tiptap placeholder convention.
      '& p.is-editor-empty:first-child::before': {
        content: 'attr(data-placeholder)',
        color: 'fg.subtle',
        float: 'inline-start',
        height: '0',
        pointerEvents: 'none',
      },
    },
    bubble: {
      display: 'flex',
      alignItems: 'center',
      gap: '2',
      bgColor: 'bg.default',
      border: 'default',
      rounded: 'md',
      shadow: 'lg',
      p: '4',
      zIndex: 'popover',
      animateIn: true,
      fadeIn: 0,
      zoomIn: 97,
    },
    counter: {
      px: '12',
      py: '4',
      color: 'fg.subtle',
      fontSize: 'xs',
      textAlign: 'end',
      borderTopWidth: '1px',
      borderTopStyle: 'solid',
      borderTopColor: 'border.muted',
    },
    // Color/emoji picker cells inside the toolbar popovers.
    swatch: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      w: '28',
      h: '28',
      rounded: 'sm',
      cursor: 'pointer',
      border: 'none',
      bgColor: 'transparent',
      _hover: { bgColor: 'bg.emphasized' },
      _focusVisible: {
        focusRingWidth: 'base',
        focusRingColor: 'accent.subtle',
      },
    },
  },
  variants: {
    size: {
      sm: {
        content: { px: '10', py: '8', minH: '96', fontSize: 'sm' },
        toolbar: { py: '4' },
      },
      md: {},
    },
  },
  defaultVariants: {
    size: 'md',
  },
} satisfies RecipeConfig
