import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import { registryItems } from '../registry/ui'

const docs = {
  button: {
    title: 'Button',
    description: 'Triggers an action or submits a form.',
    examples: [
      '<Button>Save</Button>',
      '<Button variant="outline">Cancel</Button>',
      '<Button loading>Saving</Button>',
    ],
  },
} as const

const rootDirectory = process.cwd()
const generatedDirectory = join(rootDirectory, 'apps/docs/content/components')

const writeGeneratedDoc = (name: keyof typeof docs) => {
  const item = registryItems.find((registryItem) => registryItem.name === name)

  if (item === undefined) {
    throw new Error(`Missing registry item for ${name}.`)
  }

  const doc = docs[name]
  const path = join(generatedDirectory, `${name}.mdx`)
  const content = `---
title: ${doc.title}
description: ${doc.description}
---

<!-- This file is generated by scripts/generate-docs.ts. Do not edit manually. -->

# ${doc.title}

${doc.description}

## Install

\`\`\`bash
pnpm dlx @stalk-ui/cli add @stalk-ui/${name}
\`\`\`

## Examples

${doc.examples
  .map(
    (example) => `\`\`\`tsx
${example}
\`\`\``,
  )
  .join('\n\n')}

## Registry

- Manifest: \`/r/${name}.json\`
- Recipe: \`${item.stalk.preset.recipes.join(', ')}\`
- Files: ${item.files.map((file) => `\`${file.path}\``).join(', ')}
`

  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
}

writeGeneratedDoc('button')
