// Emit apps/docs/lib/rsc-boundaries.ts: every component classified by the SAME
// predicate the registry build uses to inject 'use client', so the docs table
// always matches what `stalk-ui add` installs.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { sourceNeedsUseClient } from './build-registry'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const componentsDir = join(projectRoot, 'packages/components/src')
const outFile = join(projectRoot, 'apps/docs/lib/rsc-boundaries.ts')

const server: string[] = []
const client: string[] = []

for (const entry of readdirSync(componentsDir).sort()) {
  if (!entry.endsWith('.tsx') || entry.includes('.test.') || entry.includes('.stories.')) continue
  const source = readFileSync(join(componentsDir, entry), 'utf8')
  ;(sourceNeedsUseClient(source) ? client : server).push(entry.replace('.tsx', ''))
}

const render = (names: string[]) => names.map((name) => `  '${name}',`).join('\n')

writeFileSync(
  outFile,
  `// Generated by scripts/generate-rsc-boundaries.ts — do not edit.
// Classification mirrors the registry build's 'use client' injection.

/** Installed without 'use client': render from Server Components, zero client JS. */
export const serverComponents = [
${render(server)}
] as const

/** Installed with 'use client': render from RSC via named part imports. */
export const clientComponents = [
${render(client)}
] as const
`,
)

console.log(
  `rsc-boundaries: ${String(server.length)} server / ${String(client.length)} client components`,
)
