import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import { format } from 'prettier'

import { registryItems } from '../registry/ui'

const docs = {
  button: {
    title: 'Button',
    description: 'Triggers an action or submits a form.',
    examples: [
      '<Button>Save</Button>',
      '<Button variant="outline">Cancel</Button>',
      '<Button loading>Saving</Button>',
    ],
  },
  input: {
    title: 'Input',
    description: 'Collects short-form text from a user.',
    examples: [
      '<Input aria-label="Email" placeholder="hello@stalk-ui.com" />',
      '<Input invalid aria-label="Email" placeholder="Invalid email" />',
      '<Input disabled aria-label="Disabled input" placeholder="Disabled" />',
    ],
  },
  select: {
    title: 'Select',
    description: 'Lets a user choose one option from a native menu.',
    examples: [
      '<Select aria-label="Status"><option>Draft</option><option>Published</option></Select>',
      '<Select invalid aria-label="Status"><option>Choose a status</option></Select>',
      '<Select disabled aria-label="Disabled select"><option>Disabled</option></Select>',
    ],
  },
  textarea: {
    title: 'Textarea',
    description: 'Collects multi-line text from a user.',
    examples: [
      '<Textarea aria-label="Message" placeholder="Write a message..." />',
      '<Textarea invalid aria-label="Message" placeholder="Message is required" />',
      '<Textarea disabled aria-label="Disabled textarea" placeholder="Disabled" />',
    ],
  },
} as const

const rootDirectory = process.cwd()
const generatedDirectory = join(rootDirectory, 'apps/docs/content/components')

const writeGeneratedDoc = async (name: keyof typeof docs) => {
  const item = registryItems.find((registryItem) => registryItem.name === name)

  if (item === undefined) {
    throw new Error(`Missing registry item for ${name}.`)
  }

  const doc = docs[name]
  const path = join(generatedDirectory, `${name}.mdx`)
  const content = `---
title: ${doc.title}
description: ${doc.description}
---

<!-- This file is generated by scripts/generate-docs.ts. Do not edit manually. -->

# ${doc.title}

${doc.description}

## Install

\`\`\`bash
pnpm dlx @stalk-ui/cli add @stalk-ui/${name}
\`\`\`

## Examples

${doc.examples
  .map(
    (example) => `\`\`\`tsx
${example}
\`\`\``,
  )
  .join('\n\n')}

## Registry

- Manifest: \`/r/${name}.json\`
- Recipe: \`${item.stalk.preset.recipes.join(', ')}\`
- Files: ${item.files.map((file) => `\`${file.path}\``).join(', ')}
`

  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, await format(content, { parser: 'mdx' }))
}

for (const name of Object.keys(docs) as (keyof typeof docs)[]) {
  await writeGeneratedDoc(name)
}
